### ISSUE TITLE
[Question] Is this a right supported_key_size for ESP32?

### ISSUE THREAD

**Issue by Yoimer** [FreeRTOS/iot-reference-esp32c3#25]
Hello guys, hope you're doing quite well.

As you guys may know because of the previous issue [AWS FreeRTOS support ESP32-DevKitC](https://github.com/FreeRTOS/iot-reference-esp32c3/issues/22), I wanted to port the ESP32-C3 to ESP32 and I did it, because of your guys guidance.

About the certificates, I updated this [Old configure_esp_secure_cert.py](https://github.com/espressif/esp_secure_cert_mgr/blob/78ec22786064eb8c957087bc435ba5bb83758233/tools/configure_esp_secure_cert.py) as it is here [New configure_esp_secure_cert.py](https://github.com/Yoimer/iot-reference-esp32c3-fork/blob/d29c5270ef4942e34eacf7ba3904e3f679506adf/configure_esp_secure_cert.py)

This modification let me issue this command: `python components/esp_secure_cert_mgr/tools/configure_esp_secure_cert.py -p PORT --keep_ds_data_on_host --ca-cert CA_CERT_FILEPATH --device-cert DEVICE_CERT_FILEPATH --private-key PRIVATE_KEY_FILEPATH --target_chip esp32 --secure_cert_type cust_flash` and it worked ok.

After building, flashing and provisioning I was able to send some data to AWS as seen here: [esp32-sending.log](https://github.com/FreeRTOS/iot-reference-esp32c3/files/10529155/esp32-sending.log).

My question is:  Is this [New configure_esp_secure_cert.py](https://github.com/Yoimer/iot-reference-esp32c3-fork/blob/d29c5270ef4942e34eacf7ba3904e3f679506adf/configure_esp_secure_cert.py) a right supported_key_size for ESP32?

I just copied and pasted the  values of `esp32s2` for testing and worked pretty good.

In the past I used to copy and paste the IoT Thing certificates as referenced on the official documentation , [freertos-prereqs](https://docs.aws.amazon.com/freertos/latest/userguide/freertos-prereqs.html)

```
In a browser window, open tools/certificate_configuration/CertificateConfigurator.html.

Under Certificate PEM file, choose the ID-certificate.pem.crt that you downloaded from the AWS IoT console.

Under Private Key PEM file, choose the ID-private.pem.key that you downloaded from the AWS IoT console.

Choose Generate and save aws_clientcredential_keys.h, and then save the file in demos/include. This overwrites the existing file in the directory.

```
Looking forward to response.

Thanks in advance!

**Comment by jasonpcarroll** [comment]
Hi @Yoimer,

**Comment by Yoimer** [comment]
Hi, @jasonpcarroll. How is it going?

**Comment by jasonpcarroll** [comment]
Sorry I hit enter for a linebreak haha. But I editted my comment above.

**Comment by Yoimer** [comment]
I see @jasonpcarroll . Thanks for responding. Is it too much of a security concern having those keys in plain text, or I can just move on and not worry about them as you just commented out?

What if I untick the `Output provisioned certificates and keys` option from `idf.py menuconfig`? I guess the keys would still be plain text but not showed on the console.

Another question, how would you encrypt them just in case you do want to have those super secure?

Looking forward to response.

Thanks for supporting us!

**Comment by jasonpcarroll** [comment]
When it comes to security for those keys, you need to evaluate what's the worst thing that could happen if someone got access to them. For example, if the certificate allowed someone to access sensitive data, then you would probably want those as secure as possible. You could always get a secure element such ass https://www.microchip.com/en-us/product/atecc608a if you really want to keep those keys private. The output provisioned certificates and keys option was more of a debugging tool than anything else - that said you probably don't want that enabled in released devices :P. 
The ESP32 supports [flash encryption](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html) so at the very least you could store them in encrypted flash rather than plaintext flash. But I should mention it has known vulnerabilities (e.g. https://raelize.com/blog/espressif-systems-esp32-bypassing-flash-encryption/) You can also use flash encryption https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html
