### ISSUE TITLE
Random Block ID during OTA updates

### ISSUE THREAD

**Issue by CodeOn-ArK** [FreeRTOS/iot-reference-esp32c3#8]
Hi there!
So when I was watching the OTA update logs I saw that the AWS sends blocks in random manner. The block IDs are not serial in fashion. It even misses out several numbers in the middle. So are the payloads sent randomly as the block IDs of the payloads are random, or there's some algorithm behind it.
Regards

**Comment by divekarshubham** [comment]
Hello,

IoT Streaming Service does not guarantee the order delivery of blocks/chunks of files. They can arrive out of order and the chunks/blocks can be lost or delivered more than once due to intermittent connectivity or acknowledgement loss. The device client should handle the re-ordering of chunks using the `blockId` in each block and be resilient to duplicate messages with re-request for any missing blocks. 
The FreeRTOS OTA agent keeps track of the stream using file context to store the overall file information and a bitmap to store the chunk information. Please take a look at [requestDataHandler](https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/main/source/ota.c#L1093) to see the data request flow.
